### ISSUE TITLE
能不能出点详细教程，还是不会用

### ISSUE THREAD

**Issue by qihe7070** [chenmoand/YunKeTangCrack-Remake#1]

**Comment by chenmoand** [comment]
本身是很简单的, 其实就一个cmd 指令 下载最新版的jar包https://github.com/chenmoand/YunKeTangCrack-Remake/releases 
用cmd 输入 java -jar [我的jar包名字] 账号 密码

**Comment by chenmoand** [comment]
### 主要你需要有java运行环境

> jar 包主要作用是让你快速刷职教云mooc的课,  如果只想刷mooc就按照我上面的图片来就行
> 具体你需要将jar包放到你得eclipse 或者 idea 的库里面使用
``` java
Login login = new Login("账号", "密码")
login .doMoocOne() 单线程运行mooc刷课 比较稳定
login .doMooc(线程数量, 每次停止时间) 多线程刷mooc 容易呗封号
login .doYunKeTang(线程数量, 每次停止时间) 刷云课堂,,
```

**Comment by chaleni** [comment]
如何刷职教云 云课堂

**Comment by chenmoand** [comment]
> 如何刷职教云 云课堂

看最新readme.md

**Comment by DINGDOM** [comment]
Exception in thread "main" java.lang.NullPointerException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
        at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at fuck.mooc.YunKeTang.start(YunKeTang.java:37)
        at fuck.mooc.Login.doYunKeTang(Login.java:79)
        at fuck.mooc.Login.init(Login.java:71)
        at fuck.mooc.Start.main(Start.java:33)
Caused by: java.lang.NullPointerException
        at fuck.mooc.YunKeTang.getCellListByTopicId(YunKeTang.java:95)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
        at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at fuck.mooc.YunKeTang.getTopicListByModuleId(YunKeTang.java:78)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
        at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at fuck.mooc.YunKeTang.getModuleListByClassId(YunKeTang.java:59)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

请问这是怎么回事？

**Comment by chenmoand** [comment]
> Exception in thread "main" java.lang.NullPointerException
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> at java.lang.reflect.Constructor.newInstance(Unknown Source)
> at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
> at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
> at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
> at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> at java.util.stream.ReferencePipeline.forEach(Unknown Source)
> at fuck.mooc.YunKeTang.start(YunKeTang.java:37)
> at fuck.mooc.Login.doYunKeTang(Login.java:79)
> at fuck.mooc.Login.init(Login.java:71)
> at fuck.mooc.Start.main(Start.java:33)
> Caused by: java.lang.NullPointerException
> at fuck.mooc.YunKeTang.getCellListByTopicId(YunKeTang.java:95)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
> at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
> at java.util.concurrent.CountedCompleter.exec(Unknown Source)
> at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
> at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
> at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
> at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
> at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> at java.util.stream.ReferencePipeline.forEach(Unknown Source)
> at fuck.mooc.YunKeTang.getTopicListByModuleId(YunKeTang.java:78)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
> at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
> at java.util.concurrent.CountedCompleter.exec(Unknown Source)
> at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
> at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
> at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
> at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
> at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> at java.util.stream.ReferencePipeline.forEach(Unknown Source)
> at fuck.mooc.YunKeTang.getModuleListByClassId(YunKeTang.java:59)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
> at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
> at java.util.concurrent.CountedCompleter.exec(Unknown Source)
> at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
> at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> 
> 请问这是怎么回事？
> 我注册了新的账号并添加 资源库里面的课 可以正常刷课使用。

你是想说什么不能刷，单个尝试能吗

**Comment by chenmoand** [comment]
如果是新号的话请指定，要刷的部分，比如mooc 你就指定mooc，不要用全刷，因为会导致云课堂没有内容空指针异常

**Comment by DINGDOM** [comment]
单个也不可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "沉默"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 下午5:16
收件人: "chenmoand/YunKeTangCrack-Remake"<YunKeTangCrack-Remake@noreply.github.com&gt;; 
抄送: "　　　〇　"<775997291@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [chenmoand/YunKeTangCrack-Remake] 能不能出点详细教程，还是不会用 (#1)



 
Exception in thread "main" java.lang.NullPointerException
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
 at java.lang.reflect.Constructor.newInstance(Unknown Source)
 at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
 at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
 at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.forEach(Unknown Source)
 at fuck.mooc.YunKeTang.start(YunKeTang.java:37)
 at fuck.mooc.Login.doYunKeTang(Login.java:79)
 at fuck.mooc.Login.init(Login.java:71)
 at fuck.mooc.Start.main(Start.java:33)
 Caused by: java.lang.NullPointerException
 at fuck.mooc.YunKeTang.getCellListByTopicId(YunKeTang.java:95)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
 at java.util.concurrent.CountedCompleter.exec(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
 at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
 at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.forEach(Unknown Source)
 at fuck.mooc.YunKeTang.getTopicListByModuleId(YunKeTang.java:78)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
 at java.util.concurrent.CountedCompleter.exec(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
 at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
 at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.forEach(Unknown Source)
 at fuck.mooc.YunKeTang.getModuleListByClassId(YunKeTang.java:59)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
 at java.util.concurrent.CountedCompleter.exec(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
 at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
 at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 
请问这是怎么回事？
 我注册了新的账号并添加 资源库里面的课 可以正常刷课使用。
  
你是想说什么不能刷，单个尝试能吗

**Comment by DINGDOM** [comment]
不能，出现这个错误的账号都不能刷。选择 1&gt; 2&gt; 3&gt;&nbsp; 中任何一个都过2~3秒后出现这个信息







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "沉默"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 下午5:16
收件人: "chenmoand/YunKeTangCrack-Remake"<YunKeTangCrack-Remake@noreply.github.com&gt;; 
抄送: "　　　〇　"<775997291@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [chenmoand/YunKeTangCrack-Remake] 能不能出点详细教程，还是不会用 (#1)



 
Exception in thread "main" java.lang.NullPointerException
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
 at java.lang.reflect.Constructor.newInstance(Unknown Source)
 at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
 at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
 at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.forEach(Unknown Source)
 at fuck.mooc.YunKeTang.start(YunKeTang.java:37)
 at fuck.mooc.Login.doYunKeTang(Login.java:79)
 at fuck.mooc.Login.init(Login.java:71)
 at fuck.mooc.Start.main(Start.java:33)
 Caused by: java.lang.NullPointerException
 at fuck.mooc.YunKeTang.getCellListByTopicId(YunKeTang.java:95)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
 at java.util.concurrent.CountedCompleter.exec(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
 at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
 at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.forEach(Unknown Source)
 at fuck.mooc.YunKeTang.getTopicListByModuleId(YunKeTang.java:78)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
 at java.util.concurrent.CountedCompleter.exec(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
 at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
 at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.forEach(Unknown Source)
 at fuck.mooc.YunKeTang.getModuleListByClassId(YunKeTang.java:59)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
 at java.util.concurrent.CountedCompleter.exec(Unknown Source)
 at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
 at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
 at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 
请问这是怎么回事？
 我注册了新的账号并添加 资源库里面的课 可以正常刷课使用。
  
你是想说什么不能刷，单个尝试能吗

**Comment by chenmoand** [comment]
> 不能，出现这个错误的账号都不能刷。选择 1&gt; 2&gt; 3&gt;&nbsp; 中任何一个都过2~3秒后出现这个信息
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "沉默"<notifications@github.com&gt;; 发送时间: 2020年3月3日(星期二) 下午5:16 收件人: "chenmoand/YunKeTangCrack-Remake"<YunKeTangCrack-Remake@noreply.github.com&gt;; 抄送: "　　　〇　"<775997291@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [chenmoand/YunKeTangCrack-Remake] 能不能出点详细教程，还是不会用 (#1) Exception in thread "main" java.lang.NullPointerException at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) at java.lang.reflect.Constructor.newInstance(Unknown Source) at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source) at java.util.concurrent.ForkJoinTask.reportException(Unknown Source) at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.forEach(Unknown Source) at fuck.mooc.YunKeTang.start(YunKeTang.java:37) at fuck.mooc.Login.doYunKeTang(Login.java:79) at fuck.mooc.Login.init(Login.java:71) at fuck.mooc.Start.main(Start.java:33) Caused by: java.lang.NullPointerException at fuck.mooc.YunKeTang.getCellListByTopicId(YunKeTang.java:95) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) at java.util.concurrent.CountedCompleter.exec(Unknown Source) at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.forEach(Unknown Source) at fuck.mooc.YunKeTang.getTopicListByModuleId(YunKeTang.java:78) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) at java.util.concurrent.CountedCompleter.exec(Unknown Source) at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) at java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) at java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.forEach(Unknown Source) at fuck.mooc.YunKeTang.getModuleListByClassId(YunKeTang.java:59) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) at java.util.concurrent.CountedCompleter.exec(Unknown Source) at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) 请问这是怎么回事？ 我注册了新的账号并添加 资源库里面的课 可以正常刷课使用。 你是想说什么不能刷，单个尝试能吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请转到https://github.com/chenmoand/YunKeTangCrack-Remake/issues/3

**Comment by DINGDOM** [comment]
好的，感谢！
